"""Subsample sequences based on a YAML configuration."""
import argparse
import os
import tempfile
import yaml
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any, Dict, List, Optional, Union
from augur import filter as augur_filter
from augur.argparse_ import ExtendOverwriteDefault, SKIP_AUTO_DEFAULT_IN_HELP
from augur.errors import AugurError
from augur.io.metadata import DEFAULT_DELIMITERS, DEFAULT_ID_COLUMNS
from augur.validate import load_json_schema, validate_json


GLOBAL_CLI_OPTIONS = {
    "metadata": "--metadata",
    "metadata_chunk_size": "--metadata-chunk-size",
    "metadata_delimiters": "--metadata-delimiters",
    "metadata_id_columns": "--metadata-id-columns",
    "sequences": "--sequences",
    "sequence_index": "--sequence-index",
    "subsample_seed": "--subsample-seed",
}
"""
Mapping of argparse namespace variable name to augur filter flag.
These are sent to both intermediate and final augur filter calls.
"""


FINAL_CLI_OPTIONS = {
    "output_metadata": "--output-metadata",
    "output_sequences": "--output-sequences",
    "skip_checks": ("--skip-checks", None),
}
"""
Mapping of argparse namespace variable name to augur filter flag.
These are sent to only the final augur filter call.
"""


SAMPLE_CONFIG = {
    "exclude": "--exclude",
    "exclude_all": ("--exclude-all", None),
    "exclude_ambiguous_dates_by": "--exclude-ambiguous-dates-by",
    "exclude_where": "--exclude-where",
    "include": "--include",
    "include_where": "--include-where",
    "min_date": "--min-date",
    "max_date": "--max-date",
    "min_length": "--min-length",
    "max_length": "--max-length",
    "non_nucleotide": ("--non-nucleotide", None),
    "query": "--query",
    "query_columns": "--query-columns",
    "group_by": "--group-by",
    "group_by_weights": "--group-by-weights",
    "probabilistic_sampling": ("--probabilistic-sampling", "--no-probabilistic-sampling"),
    "sequences_per_group": "--sequences-per-group",
    "subsample_max_sequences": "--subsample-max-sequences",
}
"""
Mapping of YAML configuration key name to augur filter flag.
These are sent to only the intermediate augur filter calls.
"""


# FIXME: document that these augur filter options are unsupported:
# --priorities
# --output-log
# --output-group-by-sizes
# --output-strains
# --empty-output-reporting

def register_parser(parent_subparsers: argparse._SubParsersAction) -> argparse.ArgumentParser:
    parser = parent_subparsers.add_parser("subsample", help=__doc__)
    parser.add_argument("--metadata", required=True, help="sequence metadata")
    parser.add_argument('--metadata-delimiters', default=DEFAULT_DELIMITERS, nargs="+", action=ExtendOverwriteDefault, help="delimiters to accept when reading a metadata file. Only one delimiter will be inferred.")
    parser.add_argument('--metadata-chunk-size', type=int, default=100000, help="maximum number of metadata records to read into memory at a time. Increasing this number can speed up filtering at the cost of more memory used.")
    parser.add_argument('--metadata-id-columns', default=DEFAULT_ID_COLUMNS, nargs="+", action=ExtendOverwriteDefault, help="names of possible metadata columns containing identifier information, ordered by priority. Only one ID column will be inferred.")
    parser.add_argument("--sequences", required=True, help="sequence file")
    parser.add_argument('--sequence-index', help="sequence composition report generated by augur index. If not provided, an index will be created on the fly. This should be generated from the same file as --sequences.")
    parser.add_argument('--skip-checks', action='store_true', help="use this option to skip checking for duplicates in sequences and whether ids in metadata have a sequence entry. Can improve performance on large files.")
    parser.add_argument("--config", required=True, help="YAML subsampling config")
    parser.add_argument("--config-root", help="top-level key in config file to use for subsampling configuration (default: use entire config)" + SKIP_AUTO_DEFAULT_IN_HELP)
    parser.add_argument("--output-metadata", required=True, help="output metadata file")
    parser.add_argument("--output-sequences", required=True, help="output sequences file")
    parser.add_argument("--nthreads", type=int, default=1, help="number of threads for parallel processing")
    parser.add_argument("--subsample-seed", type=int, help="random number generator seed to allow reproducible subsampling")
    return parser


def run(args: argparse.Namespace) -> None:
    # 1. Construct argument lists for augur filter calls

    global_filter_args: List[str] = []

    for cli_option, filter_flag in GLOBAL_CLI_OPTIONS.items():
        if (value := getattr(args, cli_option)) is not None:
            _add_to_args(global_filter_args, filter_flag, value)

    config = _parse_config(args.config, args.config_root)
    defaults = config.get("defaults")
    samples = []
    include_files = []

    for name, options in config.get("samples", {}).items():
        options = _merge_options(options, defaults)
        sample = Sample(name, options, global_filter_args)
        samples.append(sample)
        include_files.append(sample.output_strains)

    combine_filter_args = [
        "--exclude-all",
        "--include", *include_files,
    ]

    combine_filter_args.extend(global_filter_args)

    for cli_option, filter_flag in FINAL_CLI_OPTIONS.items():
        if (value := getattr(args, cli_option)) is not None:
            _add_to_args(combine_filter_args, filter_flag, value)

    try:
        # 2. Run intermediate augur filter calls.
        with ThreadPoolExecutor(max_workers=args.nthreads) as executor:
            futures = {executor.submit(sample.run): sample for sample in samples}
            for future in as_completed(futures):
                sample = futures[future]
                try:
                    future.result()
                except Exception as error:
                    raise AugurError(f"Sample {sample.name!r} failed: {error}") from error

        # 3. Run the final augur filter call to combine the intermediate samples.
        _run_filter(combine_filter_args)
    finally:
        for sample in samples:
            sample.cleanup()


def _merge_options(sample_options: Dict[str, Any], defaults: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Merge sample options with default options, with sample options taking precedence.
    """
    if defaults is None:
        return sample_options

    merged_options = {**defaults, **sample_options}

    # Handle mutually exclusive options: if sample specifies one and defaults specify another, go with the sample-specific one.
    if "sequences_per_group" in sample_options and "subsample_max_sequences" in defaults:
        merged_options.pop("subsample_max_sequences", None)
    elif "subsample_max_sequences" in sample_options and "sequences_per_group" in defaults:
        merged_options.pop("sequences_per_group", None)

    return merged_options


class Sample:
    def __init__(self, name: str, config: Dict[str, Any], global_filter_args: List[str]) -> None:
        self.name = name
        self.output_strains = tempfile.NamedTemporaryFile(prefix=f"sample_{self.name}_", delete=False).name
        self.filter_args = self._construct_filter_args(config, global_filter_args)
    
    def _construct_filter_args(self, config: Dict[str, Any], global_filter_args: List[str]) -> List[str]:
        filter_args = [
            # Checks are redundant across multiple calls with the same input.
            # Checks will run once on the final augur filter call, unless explicitly skipped.
            "--skip-checks",

            # Use a single thread for each sample to simplify multithreading across samples.
            "--nthreads", "1",

            # Store outcome as a list of ids to be used by --include in the final augur filter call.
            "--output-strains", self.output_strains
        ]

        filter_args.extend(global_filter_args)

        for config_key, value in config.items():
            filter_flag = SAMPLE_CONFIG[config_key]
            _add_to_args(filter_args, filter_flag, value)

        return filter_args
    
    def run(self) -> None:
        # print_err(f"Running sample {self.name!r} with arguments {self.filter_args!r}…")
        _run_filter(self.filter_args)
        # print_err(f"Finished running sample {self.name!r}.")
    
    def cleanup(self) -> None:
        """Remove the temporary output file."""
        os.unlink(self.output_strains)


def _add_to_args(args: List[str], filter_flag: Union[str, tuple[str, Optional[str]]], value: Any) -> None:
    """Add a filter flag and its value to the arguments list."""

    # Booleans are configured by one or two flags.
    if isinstance(value, bool):
        assert isinstance(filter_flag, tuple) and len(filter_flag) == 2
        true_flag, false_flag = filter_flag
        if value is True:
            args.append(true_flag)
        elif value is False:
            if false_flag is not None:
                args.append(false_flag)
            else:
                # No false flag implies a default value of false.
                pass
        return

    # Everything else is configured by one flag.
    assert isinstance(filter_flag, str)

    # Lists and tuples are unpacked and given as strings.
    if isinstance(value, (list, tuple)):
        args.extend([filter_flag, *(str(v) for v in value)])

    # Everything else is scalar and given as strings.
    else:
        args.extend([filter_flag, str(value)])


def _run_filter(filter_args: List[str]) -> None:
    """Invoke augur filter as part of the current process."""
    parser = argparse.ArgumentParser()
    augur_filter.register_arguments(parser)
    args = parser.parse_args(filter_args)
    augur_filter.run(args)


def _parse_config(filename: str, config_root: Optional[str] = None) -> Dict[str, Any]:
    # Create a custom YAML loader
    class CustomLoader(yaml.SafeLoader):
        pass
    # treat timestamps as strings
    def string_constructor(loader, node):
        return loader.construct_scalar(node)
    CustomLoader.add_constructor('tag:yaml.org,2002:timestamp', string_constructor)

    with open(filename) as fh:
        try:
            config = yaml.load(fh, Loader=CustomLoader)
        except yaml.YAMLError as e:
            print(e)
            raise AugurError(f"Error parsing subsampling scheme {filename}")

    # If config_root is specified, extract that section from the config
    if config_root:
        if config_root not in config:
            raise AugurError(f"Config root key '{config_root}' not found in {filename}")
        config = config[config_root]

    # Validate config against schema
    try:
        schema = load_json_schema("schema-subsample-config.json")
        validate_json(config, schema, filename)
    except Exception as e:
        raise AugurError(f"Config validation failed: {e}")
    return config


# FIXME: list of potential performance optimizations
#
# - build sequence index once upfront if any sample has a sequence-based filter
#     - or replace sequence indexing entirely
#       (https://github.com/nextstrain/augur/issues/1846)
# - run default options through an initial augur filter call
#     - a proper input reuse approach such as database/parquet file would reduce the need for this
#       (https://github.com/nextstrain/augur/issues/1574)
