Setup

  $ source "$TESTDIR"/_setup.sh

Show help text

  $ ${AUGUR} filter --help
  usage: augur filter [-h] --metadata FILE [--sequences SEQUENCES]
                      [--sequence-index SEQUENCE_INDEX]
                      [--metadata-chunk-size METADATA_CHUNK_SIZE]
                      [--metadata-id-columns METADATA_ID_COLUMNS [METADATA_ID_COLUMNS ...]]
                      [--metadata-delimiters METADATA_DELIMITERS [METADATA_DELIMITERS ...]]
                      [--query QUERY]
                      [--query-columns QUERY_COLUMNS [QUERY_COLUMNS ...]]
                      [--min-date MIN_DATE] [--max-date MAX_DATE]
                      [--exclude-ambiguous-dates-by {any,day,month,year}]
                      [--exclude EXCLUDE [EXCLUDE ...]]
                      [--exclude-where EXCLUDE_WHERE [EXCLUDE_WHERE ...]]
                      [--exclude-all] [--include INCLUDE [INCLUDE ...]]
                      [--include-where INCLUDE_WHERE [INCLUDE_WHERE ...]]
                      [--min-length MIN_LENGTH] [--max-length MAX_LENGTH]
                      [--non-nucleotide] [--group-by GROUP_BY [GROUP_BY ...]]
                      [--sequences-per-group SEQUENCES_PER_GROUP | --subsample-max-sequences SUBSAMPLE_MAX_SEQUENCES]
                      [--probabilistic-sampling | --no-probabilistic-sampling]
                      [--priority PRIORITY] [--subsample-seed SUBSAMPLE_SEED]
                      [--output OUTPUT] [--output-metadata OUTPUT_METADATA]
                      [--output-strains OUTPUT_STRAINS]
                      [--output-log OUTPUT_LOG]
                      [--empty-output-reporting {error,warn,silent}]
  
  Filter and subsample a sequence set.
  
  option.* (re)
    -h, --help            show this help message and exit
  
  inputs:
    metadata and sequences to be filtered
  
    --metadata FILE       sequence metadata (default: None)
    --sequences SEQUENCES, -s SEQUENCES
                          sequences in FASTA or VCF format (default: None)
    --sequence-index SEQUENCE_INDEX
                          sequence composition report generated by augur index.
                          If not provided, an index will be created on the fly.
                          (default: None)
    --metadata-chunk-size METADATA_CHUNK_SIZE
                          maximum number of metadata records to read into memory
                          at a time. Increasing this number can speed up
                          filtering at the cost of more memory used. (default:
                          100000)
    --metadata-id-columns METADATA_ID_COLUMNS [METADATA_ID_COLUMNS ...]
                          names of possible metadata columns containing
                          identifier information, ordered by priority. Only one
                          ID column will be inferred. (default: ('strain',
                          'name'))
    --metadata-delimiters METADATA_DELIMITERS [METADATA_DELIMITERS ...]
                          delimiters to accept when reading a metadata file.
                          Only one delimiter will be inferred. (default: (',',
                          '\t'))
  
  metadata filters:
    filters to apply to metadata
  
    --query QUERY         Filter samples by attribute. Uses Pandas Dataframe
                          querying, see https://pandas.pydata.org/pandas-
                          docs/stable/user_guide/indexing.html#indexing-query
                          for syntax. (e.g., --query "country == 'Colombia'" or
                          --query "(country == 'USA' & (division ==
                          'Washington'))") (default: None)
    --query-columns QUERY_COLUMNS [QUERY_COLUMNS ...]
                          Use alongside --query to specify columns and data
                          types in the format 'column:type', where type is one
                          of ['bool', 'float', 'int', 'str']. Automatic type
                          inference will be attempted on all unspecified columns
                          used in the query. Example: region:str coverage:float.
                          (default: None)
    --min-date MIN_DATE   minimal cutoff for date, the cutoff date is inclusive;
                          may be specified as: 1. an Augur-style numeric date
                          with the year as the integer part (e.g. 2020.42) or 2.
                          a date in ISO 8601 date format (i.e. YYYY-MM-DD) (e.g.
                          '2020-06-04') or 3. a backwards-looking relative date
                          in ISO 8601 duration format with optional P prefix
                          (e.g. '1W', 'P1W') (default: None)
    --max-date MAX_DATE   maximal cutoff for date, the cutoff date is inclusive;
                          may be specified as: 1. an Augur-style numeric date
                          with the year as the integer part (e.g. 2020.42) or 2.
                          a date in ISO 8601 date format (i.e. YYYY-MM-DD) (e.g.
                          '2020-06-04') or 3. a backwards-looking relative date
                          in ISO 8601 duration format with optional P prefix
                          (e.g. '1W', 'P1W') (default: None)
    --exclude-ambiguous-dates-by {any,day,month,year}
                          Exclude ambiguous dates by day (e.g., 2020-09-XX),
                          month (e.g., 2020-XX-XX), year (e.g., 200X-10-01), or
                          any date fields. An ambiguous year makes the
                          corresponding month and day ambiguous, too, even if
                          those fields have unambiguous values (e.g.,
                          "201X-10-01"). Similarly, an ambiguous month makes the
                          corresponding day ambiguous (e.g., "2010-XX-01").
                          (default: None)
    --exclude EXCLUDE [EXCLUDE ...]
                          file(s) with list of strains to exclude (default:
                          None)
    --exclude-where EXCLUDE_WHERE [EXCLUDE_WHERE ...]
                          Exclude samples matching these conditions. Ex:
                          "host=rat" or "host!=rat". Multiple values are
                          processed as OR (matching any of those specified will
                          be excluded), not AND (default: None)
    --exclude-all         exclude all strains by default. Use this with the
                          include arguments to select a specific subset of
                          strains. (default: False)
    --include INCLUDE [INCLUDE ...]
                          file(s) with list of strains to include regardless of
                          priorities, subsampling, or absence of an entry in
                          --sequences. (default: None)
    --include-where INCLUDE_WHERE [INCLUDE_WHERE ...]
                          Include samples with these values. ex: host=rat.
                          Multiple values are processed as OR (having any of
                          those specified will be included), not AND. This rule
                          is applied last and ensures any strains matching these
                          rules will be included regardless of priorities,
                          subsampling, or absence of an entry in --sequences.
                          (default: None)
  
  sequence filters:
    filters to apply to sequence data
  
    --min-length MIN_LENGTH
                          minimal length of the sequences, only counting
                          standard nucleotide characters A, C, G, or T (case-
                          insensitive) (default: None)
    --max-length MAX_LENGTH
                          maximum length of the sequences, only counting
                          standard nucleotide characters A, C, G, or T (case-
                          insensitive) (default: None)
    --non-nucleotide      exclude sequences that contain illegal characters
                          (default: False)
  
  subsampling:
    options to subsample filtered data
  
    --group-by GROUP_BY [GROUP_BY ...]
                          categories with respect to subsample. Notes: (1)
                          Grouping by ['month', 'week', 'year'] is only
                          supported when there is a 'date' column in the
                          metadata. (2) 'week' uses the ISO week numbering
                          system, where a week starts on a Monday and ends on a
                          Sunday. (3) 'month' and 'week' grouping cannot be used
                          together. (4) Custom columns ['month', 'week', 'year']
                          in the metadata are ignored for grouping. Please
                          rename them if you want to use their values for
                          grouping. (default: None)
    --sequences-per-group SEQUENCES_PER_GROUP
                          subsample to no more than this number of sequences per
                          category (default: None)
    --subsample-max-sequences SUBSAMPLE_MAX_SEQUENCES
                          subsample to no more than this number of sequences;
                          can be used without the group_by argument (default:
                          None)
    --probabilistic-sampling
                          Allow probabilistic sampling during subsampling. This
                          is useful when there are more groups than requested
                          sequences. This option only applies when `--subsample-
                          max-sequences` is provided. (default: True)
    --no-probabilistic-sampling
    --priority PRIORITY   tab-delimited file with list of priority scores for
                          strains (e.g., "<strain>\t<priority>") and no header.
                          When scores are provided, Augur converts scores to
                          floating point values, sorts strains within each
                          subsampling group from highest to lowest priority, and
                          selects the top N strains per group where N is the
                          calculated or requested number of strains per group.
                          Higher numbers indicate higher priority. Since
                          priorities represent relative values between strains,
                          these values can be arbitrary. (default: None)
    --subsample-seed SUBSAMPLE_SEED
                          random number generator seed to allow reproducible
                          subsampling (with same input data). (default: None)
  
  outputs:
    options related to outputs, at least one of the possible representations
    of filtered data (--output, --output-metadata, --output-strains) is
    required
  
    --output OUTPUT, --output-sequences OUTPUT, -o OUTPUT
                          filtered sequences in FASTA format (default: None)
    --output-metadata OUTPUT_METADATA
                          metadata for strains that passed filters (default:
                          None)
    --output-strains OUTPUT_STRAINS
                          list of strains that passed filters (no header)
                          (default: None)
    --output-log OUTPUT_LOG
                          tab-delimited file with one row for each filtered
                          strain and the reason it was filtered. Keyword
                          arguments used for a given filter are reported in JSON
                          format in a `kwargs` column. (default: None)
    --empty-output-reporting {error,warn,silent}
                          How should empty outputs be reported when no strains
                          pass filtering and/or subsampling. (default: error)
